<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="subject.aspx.cs" Inherits="schoolmanage.subject" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">


        .auto-style1 {
            text-align: center;
        }
        .auto-style2 {
            width: 100%;
        }
        .auto-style11 {
            width: 154px;
            text-align: center;
            height: 23px;
        }
        .auto-style12 {
            width: 281px;
            height: 23px;
        }
        .auto-style13 {
            width: 197px;
        }
        .auto-style14 {
            width: 264px;
            text-align: center;
        }
        .auto-style15 {
            font-weight: bold;
        }
        .auto-style16 {
            width: 197px;
            text-align: center;
        }
        .auto-style17 {
            width: 186px;
            height: 152px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server" style="background-color: #6699FF">
        <div>
        <div>
            <asp:Panel ID="Panel1" runat="server" BackColor="#003399" Height="38px">
                <h2 class="auto-style1"><strong>
                    <asp:Label ID="Label1" runat="server" ForeColor="White" Text="SCHOOL MANAGEMENT SYSTEM"></asp:Label>
                    </strong></h2>
            </asp:Panel>
            <asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl="~/Ahome.aspx">Home</asp:HyperLink>
        </div>
        <table class="auto-style2">
            <tr>
                <td class="auto-style11">
                    <h4>Subject Information</h4>
                </td>
                <td class="auto-style12">&nbsp;</td>
                <td rowspan="7"></td>
            </tr>
            </table>
        </div>
        <p>
&nbsp;<table class="auto-style2">
                <tr>
                    <td class="auto-style16"><strong>Subject ID</strong></td>
                    <td class="auto-style14"><strong>
                        <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
                        </strong></td>
                    <td class="auto-style1" rowspan="3">
                        <img class="auto-style17" src="img/book.png" /></td>
                </tr>
                <tr>
                    <td class="auto-style16"><strong>Subject Name</strong></td>
                    <td class="auto-style14"><strong>
                        <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
                        </strong></td>
                </tr>
                <tr>
                    <td class="auto-style13"><strong></strong></td>
                    <td class="auto-style14"><strong>
                        <asp:Button ID="Button1" runat="server" CssClass="auto-style15" OnClick="Button1_Click" Text="Save" Width="116px" />
                        </strong></td>
                </tr>
            </table>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </p>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#CC9966" BorderStyle="None" BorderWidth="1px" CellPadding="4" Height="99px" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" Width="960px">
            <Columns>
                <asp:TemplateField HeaderText="Subject id">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("subid") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("subid") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Name">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("subname") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("subname") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
            <FooterStyle BackColor="#FFFFCC" ForeColor="#330099" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="#FFFFCC" />
            <PagerStyle BackColor="#FFFFCC" ForeColor="#330099" HorizontalAlign="Center" />
            <RowStyle BackColor="White" ForeColor="#330099" />
            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="#663399" />
            <SortedAscendingCellStyle BackColor="#FEFCEB" />
            <SortedAscendingHeaderStyle BackColor="#AF0101" />
            <SortedDescendingCellStyle BackColor="#F6F0C0" />
            <SortedDescendingHeaderStyle BackColor="#7E0000" />
        </asp:GridView>
    </form>
</body>
</html>
